# Generated by Django 3.1.4 on 2020-12-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('search_term', models.CharField(max_length=250)),
                ('interval_time', models.CharField(choices=[('2', '2 minutes'), ('10', '10 minutes'), ('30', '30 minutes')], default='30', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.account')),
            ],
            options={
                'ordering': ['updated_at'],
                'unique_together': {('search_term', 'interval_time')},
            },
        ),
    ]
