# @format

version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: ebay_alerts
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn ebay_alerts.wsgi:application --bind 0.0.0.0:8000 --reload -t300"
    volumes:
      - .:/code
      - ./media:/code/media
    links:
      - database
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  worker:
    image: ebay_alerts
    restart: "no"
    command:  bash -c "celery -A ebay_alerts inspect registered && celery -A ebay_alerts worker -l info"
    volumes:
      - .:/code
    links:
      - redis
      - database

  worker2:
    image: ebay_alerts
    restart: "no"
    command: celery -A ebay_alerts beat -l info
    volumes:
      - .:/code
    links:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
      - ./static_files:/static
    links:
      - web
