# @format

version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: ebay_alerts
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn ebay_alerts.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
    links:
      - database
      - redis

  redis:
    image: redis:alpine

  worker:
    image: ebay_alerts
    restart: "no"
    command: celery -A ebay_alerts worker
    volumes:
      - .:/code
    links:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
    links:
      - web
